fix: support sub configuration to be immutable to
MapColonies/config pull request #19
Opened 2024-11-26 11:41 UTC by ronenkapelian

implement deepFreeze method based on Object.freeze()

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔                                                                      |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                  |
| Chore            | ✖                                                                       |

Related issues: https://github.com/MapColonies/config/issues/18

Users can't modify the object, not the root and not the children

2024-11-26 15:05 UTC, CptSchnitz requested changes

2024-11-28 08:09 UTC, ronenkapelian commented on tests/config.spec.ts
> +    it('should returned on getAll() a full frozen configuration object ', async () => {
done

2024-11-28 08:09 UTC, ronenkapelian commented on tests/config.spec.ts
> +      expect(conf).toBeFrozen();
done

2024-11-28 11:43 UTC, CptSchnitz approved these changes

2024-11-28 16:51 UTC, netanelC approved these changes

2024-12-05 11:42 UTC, merged