fix: support null valued config attributes
MapColonies/config pull request #22
Opened 2024-12-08 13:34 UTC by ronenkapelian

deepFreeze couldn't support with null valued attributes.

Added null validation on freeze objects

| Question                | Answer                                                                          |
| ---------------- | -------------------------------------------------------------------------- |
| Bug fix         | ✔                                                                        |
| New feature     | ✖                                                                        |
| Breaking change | ✖                                                                        |
| Deprecations    | ✖                                                                        |
| Documentation   | ✖                                                                        |
| Tests added     | ✔                                                                       |
| Chore            | ✖                                                                       |

2024-12-08 16:21 UTC, netanelC approved these changes
Good Job!

2024-12-09 08:47 UTC, CptSchnitz requested changes

2024-12-09 08:47 UTC, CptSchnitz commented on tests/helpers.spec.ts
> +    it('should return object freeze', () => {
```suggestion
    it('should return frozen object', () => {
```

2024-12-09 08:47 UTC, CptSchnitz commented on tests/helpers.spec.ts
> +      expect(action).toThrow(/Cannot assign to read only property/);
only if we had an assertion to check if object is frozen 🤔

2024-12-09 08:47 UTC, CptSchnitz commented on tests/helpers.spec.ts
> +    it('should return object freeze with null value', () => {
```suggestion
    it('should return frozen object with nested null value without error', () => {
```

2024-12-09 08:47 UTC, CptSchnitz commented on tests/helpers.spec.ts
as you added tests for the function, add a test to check that deep freeze is indeed recursive

2024-12-11 07:48 UTC, ronenkapelian commented on tests/helpers.spec.ts
added

2024-12-11 07:51 UTC, CptSchnitz approved these changes

2024-12-11 07:52 UTC, CptSchnitz commented
good job son

2024-12-11 07:52 UTC, merged